### PR TITLE
Fix #25  assertModulesLoaded not matching all loaded Modules

### LINKED ISSUE #25: assertModulesLoaded not matching all loaded Modules
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.4.2

#### Summary
$modulesLoaded = array_keys($moduleManager->getLoadedModules());
#### Current behavior

assertModulesLoaded not matching all loaded Modules

#### How to reproduce

1. Add an internal dependency in a module (like 'Laminas\Mvc\I18n') with `InitProviderInterface`
2. assert for this Module with assertModulesLoaded()
 
#### Expected behavior

this will be true

### PR DESCRIPTION
**Pull request by visto9259**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

- Fixes issue #25

### CODE REVIEW

**Comment by visto9259** [comment]
This is only for #25. 
As this is my first code contribution, I will wait for review feeback to ensure the process was followed correctly before proceeding with resolving the other issues.

**Comment by visto9259** [comment]
I thought I had signoff set in my IDE.  I guess I was wrong.

File: src/PHPUnit/Controller/AbstractControllerTestCase.php [hunk 1]
```diff
@@ -380,8 +382,9 @@ public function triggerApplicationEvent($eventName)
      */
     public function assertModulesLoaded(array $modules)
     {
+        /** @var ModuleManager $moduleManager */
         $moduleManager = $this->getApplicationServiceLocator()->get('ModuleManager');
```
Comment (gsteel) [inline src/PHPUnit/Controller/AbstractControllerTestCase.php]:
```suggestion
        $moduleManager = $this->getApplicationServiceLocator()->get('ModuleManager');
        assert($moduleManager instanceof ModuleManager);
```

Try to use an assertion in cases like this - it has the same effect of telling your IDE and psalm what the type is expected to be, but with the added benefit of causing a runtime error when the type does not match with a clear assertion failure.

When the type should be verified as part of expectations for the subject under test, then PHPUnit's `self::assertInstanceOf()` method should be used.

**Comment by Xerkus** [comment]
You will need to rebase this

**Comment by visto9259** [comment]
Because of the missing signoff?  No problem

**Comment by Xerkus** [comment]
No, because it is based off of the wrong branch

File: test/_files/modules-path/with-subdir/Qux/Module.php [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+declare(strict_types=1);
+
+namespace Qux;
+
+use Laminas\ModuleManager\Feature\InitProviderInterface;
+use Laminas\ModuleManager\ModuleManagerInterface;
+use stdClass;
+
+class Module implements InitProviderInterface
```
Comment (gsteel) [inline test/_files/modules-path/with-subdir/Qux/Module.php:12]: It's OK to suppress this with `/** @psalm-suppress UnusedClass */` above the class declaration because Modules are rarely referenced by FQCN, but loaded based on file-name convention

**Comment by visto9259** [comment]
I am confused here.  
Arent't bug fixes against current release branch? which 4.10.x

**Review by gsteel — COMMENTED** [review]
Thanks @visto9259 

LGTM other than a couple of minor points.

The remaining 3 `UnusedBaselineEntry` issues can be solved by running `vendor/bin/psalm --update-baseline`

I'll leave approval for someone else who has a better memory for MVC stuff 👍

File: test/_files/modules-path/with-subdir/Qux/Module.php (hunk 2 above)
Comment (visto9259) [reply test/_files/modules-path/with-subdir/Qux/Module.php:12]: I was waiting for an OK before suppressing this one.

File: src/PHPUnit/Controller/AbstractControllerTestCase.php (hunk 1 above)
Comment (visto9259) [reply src/PHPUnit/Controller/AbstractControllerTestCase.php]: Good point.  Thanks

**Comment by visto9259** [comment]
So was I correct in using the 4.10.x branch for a bug fix?

**Comment by gsteel** [comment]
Looks to me like you worked on the patch by branching from `4.11.x`, then sent the changes to the `4.10.x` branch, hence all the `lock file maintenance` commits from renovate that are not present in `4.10.x`.

In order to clean things up, you'd need to create a new branch from `4.10.x`, then "Cherry Pick" your commits here from "Fix Laminas 25", then force push that new branch to this PR.

**Comment by visto9259** [comment]
Good grief.... you are right!  Rookie mistake.

**Comment by Xerkus** [comment]
Ignoring DCO check for non-essential commits

**Comment by Xerkus** [comment]
@visto9259 thank you
