### PR TITLE
Correction of the behavior to check a module name

### LINKED ISSUE #20: Correction of the behavior to check a module name
### Bug Report

The function `assertModuleName` currently checks for the first occurrence within the namespace.

But valid namespaces for modules are also the following:

* `\CompanyName\ModuleName`
* `\Organization\Product\Tool\Modulname`

|    Q        |   A
|------------ | ------
| Version(s)  | 3.4.2 (current)

#### Summary

* When claiming, allow module names that contain more than just one namespace-level

#### Current behavior

* only the first namespace-level is valid while assertation

#### How to reproduce

1. register a module with a namespace like `\Organization\Product\Tool\Modulname`
2. create a test with assertModuleName('Modulname')

#### Expected behavior

assertModuleName will not fail

### PR DESCRIPTION
**Pull request by nusphere**
|    Q          |   A
|-------------- | ------
| Bugfix        | yes (#20)

### Description

In this merge request, the current behavior is represented by a test case.

A module that lies within a namespace with more than 1 level is not correctly checked by the "assertModuleName".

fixes #20

### CODE REVIEW

**Comment by nusphere** [comment]
I have revised the entire assert function again so that it is properly provided as a constraint. The test coverage was used to check whether all previous behavior was retained.

Using Constrains enables the actual test to be reused cleanly.

File: src/PHPUnit/Controller/AbstractControllerTestCase.php [hunk 1]
```diff
@@ -536,40 +539,21 @@ protected function getControllerFullClassName()
 
     /**
      * Assert that the application route match used the given module
-     *
-     * @param string $module
      */
-    public function assertModuleName($module)
+    final public function assertModuleName(string $module): void
```
Comment (froschdesign) [inline src/PHPUnit/Controller/AbstractControllerTestCase.php]: If you change the public API then this is a BC break. Please revert this, otherwise the changes will have to wait until the next main version.

File: src/PHPUnit/Controller/AbstractControllerTestCase.php [hunk 2]
```diff
@@ -536,40 +539,21 @@ protected function getControllerFullClassName()
...
+        self::assertThat($module, new IsCurrentModuleNameConstraint($this));
     }
 
     /**
      * Assert that the application route match used NOT the given module
-     *
-     * @param string $module
      */
-    public function assertNotModuleName($module)
+    final public function assertNotModuleName(string $module): void
```
Comment (froschdesign) [inline src/PHPUnit/Controller/AbstractControllerTestCase.php]: The same here.

Comment (nusphere) [reply src/PHPUnit/Controller/AbstractControllerTestCase.php]: Resolved

**Comment by nusphere** [comment]
both BC breaks are solved.

**Comment by nusphere** [comment]
thank you
