### PR TITLE
Fix `assertTemplateName()` checking only the first leaf in the view model tree.

### LINKED ISSUE #3: `assertTemplateName` returns too early
`assertTemplateName` appears to return too early, and does not recursively search all child templates (see below).

```
<?php

public function myAction()
{
	$vm = new ViewModel();

	$child1 = (new ViewModel())->setTemplate('foo');
	$child2 = (new ViewModel())->setTemplate('bar');

	$vm->addChild($child1);
	$vm->addChild($child2);

	return $vm;
}

...

class testCase extends AbstractHttpControllerTestCase {
	
	public function testMyAction()
	{
		$this->dispatch('/my/action', 'GET', []);
		$this->assertTemplateName('foo'); // <-- true
		$this->assertTemplateName('bar'); // <-- false
	}

}
```

---

Originally posted by @SorX14 at https://github.com/zendframework/zend-test/issues/59

### PR DESCRIPTION
**Pull request by visto9259**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Fixes #3.

The protected function `AbstractControllerTestCase::searchTemplates()` will now traverse all view model children until the template is found, returning false if not found in any children.

### CODE REVIEW

**Comment by Xerkus** [comment]
Please use descriptive title. It will be an entry in the release notes.

File: test/PHPUnit/Controller/TemplateNameTest.php [hunk 1]
```diff
@@ -0,0 +1,42 @@
+<?php
+
+declare(strict_types=1);
+
+namespace LaminasTest\Test\PHPUnit\Controller;
+
+use LaminasTest\Test\PHPUnit\Controller\AbstractHttpControllerTestCaseTest;
+
+class TemplateNameTest extends AbstractHttpControllerTestCaseTest
```
Comment (gsteel) [inline test/PHPUnit/Controller/TemplateNameTest.php]: It'a a bit weird that you extended this test in a new class - it means that all the inherited test methods will run _again_ - I would expect a new test _method_ added to the test case around here: https://github.com/laminas/laminas-test/blob/31a9a0c9e7a6ff1d422f850dbbbb7dd664892418/test/PHPUnit/Controller/AbstractControllerTestCaseTest.php#L526
… with a method name something like `testSearchTemplatesVerifiesDeeplyNestedTemplateName`.

The content of the test method seems fine to me though 👍

**Review by gsteel — DISMISSED** [review]
Code changes LGTM but the location of the test method should be moved AFAICT.

File: test/PHPUnit/Controller/TemplateNameTest.php (hunk 1 above)
Comment (Xerkus) [reply test/PHPUnit/Controller/TemplateNameTest.php]: This should go into abstract controller test adjacent to the template assertion test or fixing template assertion test.

Comment (visto9259) [reply test/PHPUnit/Controller/TemplateNameTest.php]: Yes. I was debating this myself.
I wanted to stress that I was testing a specific case raised by the issue to make it clear.
I can move the test case as a method in `AbstractControllerTestCaseTest.php`.

Comment (visto9259) [reply test/PHPUnit/Controller/TemplateNameTest.php]: Done.
I also updated the commit messages.

**Comment by Xerkus** [comment]
Tests for the template assertion seem to be missing for a case where templates are not found, or found for `not` variant, and assertion exception is thrown. Can you also add those?

Use try catch block instead of expected exception assertion because assertion exceptions are PhpUnit's and might have special handling attached to them.

**Comment by visto9259** [comment]
That was counter intuitive.  Adding tests to check that PHPUnit fails...

**Comment by Xerkus** [comment]
Well, we are not checking that phpunit fails. We are checking that assertion succeeds.

File: test/PHPUnit/Controller/AbstractControllerTestCaseTest.php [hunk 2]
```diff
@@ -538,6 +539,52 @@ public function testAssertNotTemplateName(): void
...
+        try {
+            $this->assertNotTemplateName('child1');
+            $receivedException = false;
+        } catch (Exception $exception) {
+            $receivedException = true;
+        }
+        if (! $receivedException) {
+            $this->fail('Expected Exception not thrown');
+        }
+    }
```
Comment (Xerkus) [inline test/PHPUnit/Controller/AbstractControllerTestCaseTest.php]: Those are separate test cases so they should be split into separate tests where purpose is stated in the test name rather than a comment

Comment (visto9259) [reply test/PHPUnit/Controller/AbstractControllerTestCaseTest.php]: Tough crowd... 
Done

File: test/PHPUnit/Controller/AbstractControllerTestCaseTest.php [hunk 3]
```diff
@@ -538,6 +539,66 @@ public function testAssertNotTemplateName(): void
...
+     */
+    public function testAssertTemplateNameFailsWhenNotFound(): void
+    {
+        $this->dispatch('/childview');
+
+        try {
+            $this->assertTemplateName('foo');
+            $receivedException = false;
+        } catch (Exception $exception) {
+            $receivedException = true;
```
Comment (Xerkus) [inline test/PHPUnit/Controller/AbstractControllerTestCaseTest.php]: To ensure correct exception was received assert the message content.

This test would fail and uncover the fact that no message is provided in the assertion implementation.

File: test/PHPUnit/Controller/AbstractControllerTestCaseTest.php [hunk 4]
```diff
@@ -538,6 +539,66 @@ public function testAssertNotTemplateName(): void
...
+        }
+        if (! $receivedException) {
+            $this->fail('Expected Exception not thrown');
+        }
```
Comment (Xerkus) [inline test/PHPUnit/Controller/AbstractControllerTestCaseTest.php]: you can return early in the catch block and then no conditional flag is needed.

File: test/PHPUnit/Controller/AbstractControllerTestCaseTest.php [hunk 5]
```diff
@@ -538,6 +539,66 @@ public function testAssertNotTemplateName(): void
...
+    /**
+     * Check that the assertion fails when template is NOT found where it was supposed to found
+     */
+    public function testAssertTemplateNameFailsWhenNotFound(): void
+    {
+        $this->dispatch('/childview');
+
+        try {
+            $this->assertTemplateName('foo');
+            $receivedException = false;
```
Comment (Xerkus) [inline test/PHPUnit/Controller/AbstractControllerTestCaseTest.php]: Variable used outside of the block should be defined outside of the block for the code quality. Even if it is defined in all the code branches (currently).

File: test/PHPUnit/Controller/AbstractControllerTestCaseTest.php [hunk 6]
```diff
@@ -538,6 +539,66 @@ public function testAssertNotTemplateName(): void
...
+     */
+    public function testAssertNotTemplateNameFailsWhenFound(): void
+    {
+        $this->dispatch('/childview');
+
+        try {
+            $this->assertNotTemplateName('child1');
+            $receivedException = false;
+        } catch (Exception $exception) {
+            $receivedException = true;
```
Comment (Xerkus) [inline test/PHPUnit/Controller/AbstractControllerTestCaseTest.php]: Same changes as for the previous test.

**Review by Xerkus — CHANGES_REQUESTED** [review]
Did you think this was over? :wink:

There are some QA changes I want you to address before it is ready.

File: test/PHPUnit/Controller/AbstractControllerTestCaseTest.php (hunk 4 above)
Comment (visto9259) [reply test/PHPUnit/Controller/AbstractControllerTestCaseTest.php]: Boy, do I feel like a junior developer right now...

File: test/PHPUnit/Controller/AbstractControllerTestCaseTest.php (hunk 5 above)
Comment (visto9259) [reply test/PHPUnit/Controller/AbstractControllerTestCaseTest.php]: Yep I felt that this was not very good...

File: test/PHPUnit/Controller/AbstractControllerTestCaseTest.php (hunk 4 above)
Comment (visto9259) [reply test/PHPUnit/Controller/AbstractControllerTestCaseTest.php]: Before I commit again, is this better?

```php
public function testAssertTemplateNameFailsWhenNotFound(): void
    {
        $this->dispatch('/childview');

        try {
            $this->assertTemplateName('foo');
        } catch (Exception $exception) {
            return;
        }
        $this->fail('Expected Exception not thrown');
    }
```

Comment (Xerkus) [reply test/PHPUnit/Controller/AbstractControllerTestCaseTest.php]: Yes. This is better.

Also, the catch block should be for phpunit's `PHPUnit\Framework\ExpectationFailedException` as any other exception would not be from assertion doing its work

**Review by Xerkus — APPROVED** [review]

**Comment by Xerkus** [comment]
CI run stuck

**Comment by Xerkus** [comment]
@visto9259 thank you
